# Configuration for AEROSPACE 
# See https://nikitabobko.github.io/AeroSpace/guide#configuring-aerospace for the full list

# Using borders a separate mac app
# this add a green border to the active window
# which helps when the layout is split
after-startup-command = [
  'exec-and-forget borders active_color=0xFF00FF000 width=5.0'
]
start-at-login = false

# This two normalization make sures the correct splitting direction be used
# see https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# No hiding from aerospace
automatically-unhide-macos-hidden-apps = true 

# The space around each window (that are not in floating mode) 
accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

# Move the mouse when changing workspace across monitor
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# When in tiles mode, configure the space between tiles
[gaps]
inner.horizontal = 20 
inner.vertical =  20 
outer.left = 20
outer.right = 20
outer.top = 20
outer.bottom = 20

[mode.main.binding]
# Switch between tiles, accordion and floating mode
alt-shift-backslash = 'layout tiles horizontal vertical'
alt-shift-comma = 'layout accordion horizontal vertical'
alt-shift-p = 'layout floating tiling'

# Navigate windows in a workspace
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move the windows in a workspace
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Resize the windows in a workspace
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'
alt-shift-minus = 'resize smart -200'
alt-shift-equal = 'resize smart +200'

# Switch between workspace
alt-1 = 'workspace main'
alt-2 = 'workspace secondary'
alt-3 = 'workspace third'
alt-4 = 'workspace four'
alt-0 = 'workspace ten'
alt-9 = 'workspace nine'
alt-8 = 'workspace eight'
alt-v = 'workspace view-only'
alt-m = 'workspace messaging'
alt-s = 'workspace sound' 
alt-d = 'workspace database' 
alt-g = 'workspace godspeed'
alt-b = 'workspace heptabase'
alt-x = 'workspace ghostty'
alt-c = 'workspace arc-main'

# Move windows between workspace
alt-shift-1 = 'move-node-to-workspace main'
alt-shift-2 = 'move-node-to-workspace secondary'
alt-shift-3 = 'move-node-to-workspace third'
alt-shift-4 = 'move-node-to-workspace four'
alt-shift-0 = 'move-node-to-workspace ten'
alt-shift-9 = 'move-node-to-workspace nine'
alt-shift-8 = 'move-node-to-workspace eight'
alt-shift-v = 'move-node-to-workspace view-only'
alt-shift-m = 'move-node-to-workspace messaging'
alt-shift-s = 'move-node-to-workspace sound'
alt-shift-d = 'move-node-to-workspace database'
alt-shift-g = 'move-node-to-workspace godspeed'
alt-shift-b = 'move-node-to-workspace heptabase'
alt-shift-x = 'move-node-to-workspace ghostty'
alt-shift-c = 'move-node-to-workspace arc-main'

# Go to last visited workspave
alt-tab = 'workspace-back-and-forth'

# Move the workspace to the next monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Switch to service mode, which will have another set of binding
alt-shift-semicolon = 'mode service'

[mode.service.binding]
# Reload aerospace config, aka this file
esc = ['reload-config', 'mode main']

# Force a bunch of apps to use floating mode when it opens
[[on-window-detected]]
if.app-name-regex-substring = 'Calendar'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Password'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Setting'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'Clock'
run = 'layout floating'

[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = ["layout floating", "move-node-to-workspace ghostty"]

# Force a bunch of apps to be in a ceretain workspace when it opens
[[on-window-detected]]
if.app-name-regex-substring = 'Datagrip'
run = 'move-node-to-workspace database'

[[on-window-detected]]
if.app-name-regex-substring = 'Compass'
run = 'move-node-to-workspace database'

[[on-window-detected]]
if.app-name-regex-substring = 'Godspeed'
run = 'move-node-to-workspace godspeed'

[[on-window-detected]]
if.app-name-regex-substring = 'Heptabase'
run = 'move-node-to-workspace heptabase'

# Force messaging workspace to only be in the built in monitor
# I often need to share screen on a TV, 
# and aerospace always move my messaging workspace to the TV monitor.
[workspace-to-monitor-force-assignment]
messaging = 'built-in'
sound = 'built-in'
view-only = 'built-in'
