enter_accept = true 
auto_sync = false
update_check = false
style = "full"
invert = false 
keymap_mode = "vim-normal"
keymap_cursor = { emacs = "blink-block", vim_insert = "blink-block", vim_normal = "steady-bar" }

[stats]
common_prefix = ["sudo"]
ignored_commands = [
  "cd",
  "ls",
  "vi"
]

